tadzik/panda

lib/Panda/Ecosystem.pm

UK Virgin ISP has blocked p6c.org (which I will complain about).  This patch gives a better error message in this case.

handle malformed JSON project file case error handling better

---

README.md

1. Removed references to `Pies` (seems really outdated to keep around)
2. Windows installation is the same as linux (no need for wget)
3. Update windows command to include double quotes to correctly group supplied flags/arguments
4. Update referenced installation file path to /share from /languages

update README for new paths, windows installation, old info

---

lib/Panda/Fetcher.pm

Since the HEAD of a repo may be where development happens and a
particular tag or commit will correspond to a particular version of a
module, allow URLS of the form  git://github.com/foo/bar@v1.2.3
to checkout the commit specified by "v1.2.3" once the repo is cloned.

Add a way to specify a particular commit in URLs

---

lib/Panda.pm

This fixes panda bootstrap on windows.

Allow a '\' character for local installs

---

lib/Panda/Installer.pm

MoarVM uses `mmap()` to map bytecode files into memory.  Unfortunately,
this means that if a process overwrites the contents of that bytecode
file during the operation of a Perl 6 program using it (for example,
Panda updating its own dependencies), the memory map will seemingly
change out from under MoarVM, usually resulting in a crash.  Unlinking
the destination first doesn't harm processes that have loaded that
bytecode; it just guarantees that the new version gets its own inode
and doesn't mess with currently running Perl 6 processes.
Note that this is non-atomic, so a Perl 6 process started at just
the wrong time will try to open the bytecode file between the unlinking
and the creation of the copy, or worse yet, open and use the file
while it's being written.  The risk of this is low …

Unlink destination before performing copy on non-Windows

---

lib/Panda.pm

Currently, tests for reverse dependencies are always run,
regardless of whether --notests was specified

Respect --notests when installing reverse dependencies

---

lib/Panda/Ecosystem.pm

Quick hack to prevent  the projects.json getting overwritten if the server responds other than 200

Don't bother writing projects file if not 200 response

---

lib/Panda/App.pm

The `.for` method has been deprecated in favour of the `.flatmap` method.
The deprecated method will be removed in Rakudo 2015.09.  This change
removes the deprecation warning that appears when running the 'list'
command.

Replace .for method with .flatmap

---

lib/Panda/Builder.pm
lib/Panda/Project.pm
lib/Panda/Tester.pm

This is another attempt at separating the standard output and error of a build.
This keeps both streams interleaved and preserves existing behavior, but also offers separate stdout and stderr attributes for tools to use.

Dont cross the streams - Proc::Async

---

lib/Panda/Builder.pm

This is something I was using for testing, and is not portable.

Remove ANSI terminal color codes

---

lib/Panda/Builder.pm

Hi,
noticed this when looking at a problem with the BSON module.

Fix regex so it will properly match e.g. "BSON::EDC-Tools"

---

lib/Panda/Builder.pm
lib/Panda/Common.pm
lib/Panda/Tester.pm

Fixes panda on the JVM.
Note that `shell` currently has a bug where it assumes all commands are successful if `:out` is provided, so this should probably not be merged until that has been fixed.

Fall back to shell() if Proc::Async is not available

---

lib/Panda/Builder.pm
lib/Panda/Bundler.pm
lib/Panda/Tester.pm

When the change to use Proc::Async was made it didn't take into account that Panda::Bundler was setting $*EXECUTABLE to add the -MPanda::DepTracker and this was being passed directly to Proc::Async as the command which doesn't work.
This adds a :@deps argument to Panda::Builder.build and Panda::Tester.test that allows the caller to specify a list of modules that should be loaded with '-M'  and Panda::Bundler.bundle passes Panda::DepTracker.
This is a rework of  #184 which didn't merge cleanly with the current state of master/HEAD

Repair "gen-meta" (again)

---

lib/Panda.pm
lib/Panda/Common.pm
lib/Panda/Ecosystem.pm
lib/Panda/Installer.pm
t/installer.t

Fixed up most cases found by tests and by trying bootstrap.
On my machine, i was able to successfully bootstrap panda on glr given the patched File::Find and Shell::Command deps which i PR'ed on their respective repos. JSON::Tiny has the fixes alredy pushed upstream.

Add compatibility with GLR

---

ext/File__Find/META.info
ext/File__Find/README.md
ext/File__Find/lib/File/Find.pm
ext/File__Find/t/01-file-find.t

7a683abb9879 Merge pull request #11 from flussence/master
ae88ab4fb768 Kebab-case dies_ok to fix deprecation
8c39dec86874 Merge pull request #10 from paultcochrane/pr/expand-readme-synopsis
c3e30d319099 Add examples of the name, type and keep-going options to SYNOPSIS
15277eea7f75 Add comments explaining SYNOPSIS examples
8907c618610e Fix minor typos in README.md
034d8e24c715 Fill in META.info
522363b2ac2b Specify what exactly exclude should be and how it's handled
git-subtree-dir: ext/File__Find
git-subtree-split: 7a683abb9879738d671eb5a09923096a429eeda7

Squashed 'ext/File__Find/' changes from 119e620270cb..7a683abb9879

---

bootstrap.pl

Without this change, bootstrap.pl dies with:
Type check failed in assignment to '$prefix'; expected 'Str' but got 'List'
in sub MAIN at bootstrap.pl:22
in block <unit> at bootstrap.pl:7
Since https://github.com/rakudo/rakudo/commit/63a883fcce

grep now uses single-arg-rule slurpy

---

bin/panda

Slurpy parameters should follow optional parameters. Constraint slurpy to exist so that typing "panda" on its own returns usage rather than nothing.

Fix "panda" with no args to display usage

---

lib/Panda/Bundler.pm
lib/Panda/Reporter.pm

This PR will fix #222 (`Unexpected named parameter 'pretty' passed`), which was introduced by my previous PR #214. Sorry...
In #214, I didn't realize that panda used two different to-json() functions, rakudo core to-json() and JSON::Fast::to-json().
I think we should use one of them, and rakudo core to-json() does not support one-line json.
So this PR changes the code to use JSON::Fast::to-json entirely.

use JSON::Fast::to-json entirely

---

bin/panda

These commits add a custom `&USAGE` for panda to use (whose organization, formatting, etc. can be modified as necessary, this is just what I came up with for a more verbose/helpful `USAGE`), adds the `help` action for printing the `USAGE`, and removes the `panda module::name` → `panda install module::name` shortcut.
The last one, removing the `install` shortcut, is so that attempted actions that don't exist will produce a help message, instead of thinking it's a package (before the commit adding the `help` action, trying `panda help` caused panda to try to install a package named `help`). The alternative could've been to require actions written as `--install`, `--installdeps`, etc. (or some other prefix/suffix), but that would have caused more issues in terms of changed syntax.

Improve bin/panda USAGE and invalid arguments

---

lib/Panda/Tester.pm

`t/tester.t` will be failed if `--verbose` or `--failures` option
is written in `.proverc`, because Panda::Tester uses `prove` through
command execution.
That command execution uses `.proverc` implicitly, so it is necessary
to be disable that in order to make tests successful.
So added `--norc` option into prove command.

Add `--norc` option into `prove` command that is used on Panda::Tester

---

lib/Panda/Installer.pm

This is an attempt at fixing panda situation on windows because of the missing .bat file.

Fix #112: .bat launchers for Win32 environment

---

lib/Panda/Ecosystem.pm

I wouldn't say this should be a final change but it definitely gets it working again.
It appears that .get is getting more than expected.

Expedient fix to work "\r\n" grapheme change

---

lib/Panda/Ecosystem.pm

It would be much nicer if someone made a nice HTTP::Tiny but this fixes the last bit of fallout.

Fix back fetch projects.json after \r\n changes settled

---

bin/panda

17:16] < stmuk_> Usage: panda <action> [options]
[17:17] < stmuk_> but I have to do panda --notests install 007
[17:17] < stmuk_> I think it should be Usage: panda [options] <action>?

options have to precede actions now

---

rebootstrap.pl

Whether CUSTOM_LIB should contain objects rather than strings is probably
a matter to investigate, but this makes panda get further in either case until
that gets worked out.

quick fix for one CURLI problem

---

lib/Panda/Bundler.pm

TimToady wrote https://github.com/rakudo/rakudo/commit/625d1c5116 today.  With that, Panda breaks at compile time without access to EVAL.  This restores it.  The pragma could maybe be lexically scoped more, but file scope looked fine to me.

Add MONKEY-SEE-NO-EVAL pragma to access EVAL after change today

---

.gitignore
bin/panda

Should fix "cannot unbox type object" with installdeps.  This is basically the same as that for install but actually adds "force" to the installdeps which is possibly useful anyway.

Apply :$force change to installdeps

---

lib/Panda/App.pm

`mkdir` on MoarVM already does the same thing as `mkpath` and does not fail in case of preexisting directories, so no need to check beforehand.
Fixes @mojca issues according to http://irclog.perlgeek.de/perl6/2015-12-30#i_11800996
Supersedes #264

try to unconditionally make $pandadir via .mkdir instead of &mkpath

---

lib/Panda.pm

`--prefix` options doesn't get pased to the install for deps. For normal install it works correctly.
Before:
```
$ rm -rf here; mkdir here
$ panda --prefix="inst#here" installdeps .
==> Test depends on Acme::Meow
==> Fetching Acme::Meow
==> Building Acme::Meow
==> Testing Acme::Meow
t/00-load.t .. ok
t/01-fun.t ... ok
All tests successful.
Files=2, Tests=7,  2 wallclock secs ( 0.02 usr  0.00 sys +  1.98 cusr  0.13 csys =  2.13 CPU)
Result: PASS
==> Installing Acme::Meow
==> Successfully installed Acme::Meow
$ tree here
here
└── panda
├── projects.json
└── state
1 directory, 2 files
```
After:
```
$ rm -rf here; mkdir here
$ panda --prefix="inst#here" installdeps .
==> Test depends on Acme::Meow
==> Fetching Acme::Meow
==> Building Acme::Meow
==> Testing Acme::Meow
t/00-load.t .. ok …
```

Use prefix when installing deps

---

lib/Panda/Reporter.pm

utf-8
This fixes the current breakage of smoke reports for Compress::Zlib::Raw and downstream
modules:
```
PANDA_SUBMIT_TESTREPORTS=1 perl6 -I ../panda/lib/ ../panda/bin/panda --force --notests install Compress::Zlib::Raw
==> Fetching Compress::Zlib::Raw
==> Building Compress::Zlib::Raw
Found system zlib library.
==> Installing Compress::Zlib::Raw
Potential difficulties:
In 'deflateBound' routine declaration - Not an accepted NativeCall type for parameter [2]  : int
--> For Numerical type, use the appropriate int32/int64/num64...
at /home/david/git/rakudo/install/share/perl6/site/sources/FE992CD05870773DBDC05495667F45237164C142:155
------> ong is native(&find-lib) is export { * }⏏<EOL>
... # etc
==> Test report submitted as: http://testers.perl6.org/reports/invalid character encountered …
```

send smoke reports JSON as strict utf-8

---

ext/JSON__Fast/META6.json
ext/JSON__Fast/lib/JSON/Fast.pm
ext/JSON__Fast/t/04-roundtrip.t

Hi,
The fix to JSON::Fast was required to allow some of my modules to use it rather than JSON::Tiny, unfortunately this creates a problem as some of the tests will fail with the earlier version that is being installed by panda and it is not possible to get panda to install the newer version as a dependency at the current time.
Thanks.

Update JSON::Fast to v0.4

---

lib/Panda/Project.pm

Building Rakudo head I get the following:
==> Installing panda
==> Successfully installed panda
Saw 1 occurrence of deprecated code.
================================================================================
Sub from-json (from GLOBAL) seen at:
~/.rakudobrew/moar-nom/panda/lib/Panda/Project.pm (Panda::Project), line 23
Please use JSON::Fast, JSON::Tiny or JSON::Pretty from https://modules.perl6.org/ instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!
This appears to follow a refactor to JSON::Fast already underway.

Avoid Rakudo internals deprecation warning

---

bin/panda

Using the new Rakudo $*MAIN-ALLOW-NAMED-ANYWHERE, this fixes #256, #232, #226.

Use the new rakudo option to put flags after cmd

---

lib/Panda/Common.pm

Add a "sink" for the sink context use of ```$p.result``` thus avoiding the warning.
Fixes #329

Fix warning in Panda::Common
